# https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: false
dist: trusty
language: node_js
node_js:
  - "10"
before_script:
  - node --version
  - npm --version
  - openssl version
  - openssl list -digest-algorithms
script:
  - npm run lint
  - npm test
after_script: "npm run coverage"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
