# http://www.appveyor.com/docs/appveyor-yml

image:
  - Visual Studio 2022

environment:
  NODE_SKIP_PLATFORM_CHECK: 1
  nodejs_version: "24"

version: "{build}-{branch}"

init:
  - git config --global core.longpaths true

clone_depth: 1

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_test:
  - node --version
  - npm --version
  - openssl version
  - openssl list-message-digest-algorithm

test_script:
  - npm run lint
  - npm test

build: off
