name: Node.js v22 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Lint and test
      run: |
        npm run lint
        npm test
        npm run coverage

    - name: Upload code coverage to codecov
      # https://github.com/marketplace/actions/codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.lcov

    - name: Upload code coverage to DeepSource
      # https://docs.deepsource.com/docs/languages/javascript
      run: |
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage.lcov
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}