name: Node.js v22 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - run: npm ci
    - run: npm run lint
    - run: npm test
            
    #- name: Frogbot by JFrog
    #  uses: jfrog/frogbot@v2.21.4
    #  env:
    #    JF_URL: ${{ secrets.JF_URL }}
    #    JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    #    JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    JF_FAIL: "FALSE" # Do not fail the build
