name: Node.js v20 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run lint
    - run: npm test
    - name: Frogbot by JFrog
      uses: jfrog/frogbot@v2.21.0
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JF_FAIL: "FALSE" # Do not fail the build
